var members = [
  {
    name: "Azza Abouzied",
    title: "Principal Investigator",
    website: "http://azza.azurewebsites.net/",
    image: "images/members/azza.jpg",
    email: "azza@nyu.edu",
    type: "PI",
  },
  {
    name: "Miro Mannino",
    title: "Research Engineer",
    image: "images/members/miro.jpg",
    email: "miro.mannino@nyu.edu",
    website: "https://miromannino.com/",
    type: "RA",
  },
  {
    name: "Anh Mai",
    title: "Research Assistant",
    image: "images/members/anh.jpg",
    email: "alm818@nyu.edu",
    website: "",
    year: 2020,
    type: "RA",
  },
  {
    name: "Zain Tariq",
    title: "Research Assistant",
    image: "images/members/zain.jpg",
    email: "zain.tariq@nyu.edu",
    website: "https://www.zaintq.com/",
    year: 2020,
    type: "RA",
  },
  // {
  //     name: "Hashim Hayat",
  //     title: "Research Assistant",
  //     type: "RA",
  //     year: "2020",
  //     image: "images/members/hashim.jpg",
  //     email: "hh1316@nyu.edu",
  //     website: "https://hashimhayat.com",
  // },
  // {
  //     name: "Ahmad S Chatha",
  //     title: "PhD Student",
  //     type: "phd",
  //     year: "2024",
  //     image: "images/members/ahmad.jpg",
  //     email: "asc386@nyu.edu",
  //     website: ""
  // },
  {
    name: "Matteo Brucato",
    title: "PhD Candidate - UMass",
    year: 2021,
    type: "phd",
    image: "images/members/matteo.png",
    email: "matteo@cs.umass.edu",
    website: "https://people.cs.umass.edu/~matteo/",
  },
  {
    name: "Maeda Hanafi",
    title: "PhD Candidate",
    type: "phd",
    year: 2020,
    image: "images/members/maeda.jpg",
    email: "mh4047@nyu.edu",
    website: "https://maeda.herokuapp.com/",
  },
  {
    name: "Junior Garcia",
    title: "Research Assistant",
    image: "images/members/junior.jpg",
    email: "jfg388@nyu.edu",
    website: "https://www.juniorfranciscogarcia.com",
    year: 2021,
    type: "RA",
  },
  {
    name: "Lauren McMillen",
    title: "Student Researcher",
    image: "images/members/lauren.jpg",
    email: "lm3623@nyu.edu",
    year: 2022,
    type: "undergrad",
  },
  {
    name: "Yousra El Hassan",
    title: "Student Researcher",
    image: "images/members/yousra.jpg",
    email: "yeh218@nyu.edu",
    website: "",
    year: 2020,
    type: "undergrad",
  },
  {
    name: "Bokang Jia",
    title: "Student Researcher",
    image: "images/members/jia.png",
    email: "bj798@nyu.edu",
    website: "",
    year: 2021,
    type: "undergrad",
  },
  {
    name: "Min Kyu Jung",
    title: "Student Researcher",
    image: "images/members/minkyu.jpg",
    email: "mkj280@nyu.edu",
    website: "",
    year: 2020,
    type: "undergrad",
  },
  {
    name: "Reem Hazim",
    title: "Student Researcher",
    image: "images/members/reem.jpg",
    email: "rh3015@nyu.edu",
    year: 2022,
    type: "undergrad",
  },
  // {
  //   name: "Cole Beasley",
  //   title: "Student Researcher",
  //   email: "crb596@nyu.edu",
  //   year: 2022,
  //   type: "undergrad",
  // },
  // {
  //   name: "Muhammad Anas",
  //   title: "Student Researcher",
  //   email: "maj524@nyu.edu>",
  //   year: 2022,
  //   type: "undergrad",
  // },
  {
    name: "Phillip Wang",
    title: "Student Researcher",
    image: "images/members/phillip.jpg",
    email: "pw1287@nyu.edu",
    website: "https://phillipw.info/",
    year: 2022,
    type: "undergrad",
  },
  // {
  //   name: "Liam Richards",
  //   title: "Student Researcher",
  //   email: "lrm444@nyu.edu",
  //   year: 2022,
  //   type: "undergrad",
  // },
  {
    name: "Jacqueline Abalo",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Christian Munoz",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Abhimanyu Vasishth",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Mark Surnin",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Andrew Callendar",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Jaehurn Nam",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Yuhui Dai",
    type: "undergrad",
    year: 2017,
    title: "Undergraduate Researcher",
  },
  {
    name: "Moiri Gambioni",
    type: "undergrad",
    year: 2018,
    title: "Undergraduate Researcher",
  },
  {
    name: "Yana Chala",
    type: "undergrad",
    year: 2019,
    title: "Undergraduate Researcher",
  },
  {
    name: "Shantanu Bhatia",
    type: "undergrad",
    year: 2019,
    title: "Undergraduate Researcher",
  },
  {
    name: "Emil Goldsmith Olesen",
    type: "undergrad",
    year: 2019,
    title: "Undergraduate Researcher",
  },
];
