var members =  [
    {
        id: 0,
        name: "Azza Abouzied",
        title: "Principal Investigator",
        website: "http://azza.azurewebsites.net/",
        image: "images/members/azza.jpg",
        email: "azza@nyu.edu",
        type: "PI",
    },
    {
        id: 1,
        name: "Maeda Hanafi",
        title: "PhD Candidate",
        type: "phd",
        year: "2020",
        image: "images/members/maeda.jpg",
        email: "mh4047@nyu.edu",
        website: "https://maeda.herokuapp.com/",
    },
    {
        id: 19,
        name: "Matteo Brucato",
        title: "PhD Candidate - UMass",
        year: "2020",
        type: "phd",
        image: "images/members/matteo.png",
        email: "matteo@cs.umass.edu",
        website: "https://people.cs.umass.edu/~matteo/",
    },
    {
        id: 2,
        name: "Ahmad S Chatha",
        title: "PhD Student",
        type: "phd",
        year: "2024",
        image: "images/members/ahmad.jpg",
        email: "asc386@nyu.edu",
        website: ""
    },
    {
        id: 3,
        name: "Miro Mannino",
        title: "Research Assistant",
        image: "images/members/miro.jpg",
        email: "miro.mannino@nyu.edu",
        website: "https://miromannino.com/",
        type: "RA"
    },
    {
        id: 4,
        name: "Anh Mai",
        title: "Student Researcher",
        image: "images/members/anh.jpg",
        email: "alm818@nyu.edu",
        website: "",
        year: 2020,
        type : "undergrad"
    },
    {
        id: 5,
        name: "Yousra El Hassan",
        title: "Student Researcher",
        image: "images/members/yousra.jpg",
        email: "yeh218@nyu.edu",
        website: "",
        year: 2020,
        type : "undergrad"
    },
    {
        id: 6,
        name: "Bokang Jia",
        title: "Student Researcher",
        image: "images/members/jia.png",
        email: "bj798@nyu.edu",
        website: "",
        year: 2021,
        type : "undergrad"
    },
    {
        id: 7,
        name: "Min Kyu Jung",
        title: "Student Researcher",
        image: "images/members/min.jpg",
        email: "mkj280@nyu.edu",
        website: "",
        year: 2020,
        type : "undergrad"
    },

    {
        id: 8,
        name: "Jacqueline Abalo",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 9,
        name: "Christian Munoz",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 10,
        name: "Abhimanyu Vasishth",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 11,
        name: "Mark Surnin",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 12,
        name: "Andrew Callendar",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 13,
        name: "Jaehurn Nam",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 14,
        name: "Yuhui Dai",
        type: "undergrad",
        year: "2017",
        title: "Undergraduate Researcher",
    },
    {
        id: 15,
        name: "Moiri Gambioni",
        type: "undergrad",
        year: "2018",
        title: "Undergraduate Researcher",
    },
    {
        id: 16,
        name: "Yana Chala",
        type: "undergrad",
        year: "2019",
        title: "Undergraduate Researcher",
    },
    {
        id: 17,
        name: "Shantanu Bhatia",
        type: "undergrad",
        year: "2019",
        title: "Undergraduate Researcher",
    },
    {
        id: 18,
        name: "Emil Goldsmith Olesen",
        type: "undergrad",
        year: "2019",
        title: "Undergraduate Researcher",
    }
    ];
