var news =  [
    {
        headline: "Maeda Hanafi has successfully defended her thesis on March 23, 2020. Congrats Dr. Hanafi!",
        link: "",
        abstract: "",
        date: "March 24, 2020",
    },
    {
        headline: "Our work on Realistic Data Generation with Synner was accepted for a Demo to SIGMOD 2020",
        link: "",
        abstract: "",
        date: "February 20, 2020",
    },
    {
        headline: "Our work on Stochastic Package Queries in Probabilistic Databases was accepted to SIGMOD 2020",
        link: "",
        abstract: "",
        date: "January 20, 2020",
    },
    {
        headline: "Azza Abouzied, Sihem Amer-Yahia and Zack Ives are chairing HILDA 2020",
        link: "",
        abstract: "",
        date: "October 28, 2019",
    },
    {
        headline: "Miro Mannino presented Synner at UIST in New Orleans",
        link: "http://uist.acm.org/uist2019/program/#Day2",
        abstract: "",
        date: "October 20, 2019",
    },
    {
        headline: "Professor Azza Abouzied wins the Test of Time Award at VLDB 2019",
        link: "https://nyuad.nyu.edu/en/academics/divisions/science/faculty/azza-abouzied/news/test-of-time-award.html",
        abstract: "VLDB Test of Time Award paper is selected from the VLDB Conference from 10 to 12 years earlier that best meets the “test of time”. The committee evaluates the impact of the paper in practice, e.g., in products and services. Impact on the academic community demonstrated through significant follow-through research.",
        date: "August 29, 2019",
    },
    {
        headline: "Professor Azza Abouzied delivers keynote at DSIA 2018 (IEEE VIS) on building example-driven interfaces for data tasks",
        link: "https://www.interactive-analysis.org/year/2018/",
        abstract: "",
        date: "October 21, 2018",
    },
    {
        headline: "Miro Mannino & Maeda Hanafi present their work at HILDA in Amsterdam",
        link: "https://hilda.io/2019/",
        abstract: "",
        date: "July 5, 2019",
    },
    {
        headline: "Miro Mannino presents Qetch as SIGMOD in Houston",
        link: "https://sigmod2018.org/",
        abstract: "",
        date: "June 13, 2018",
    },
    {
        headline: "Qetch paper wins Best Paper Award",
        link: "https://dl.acm.org/citation.cfm?id=3173962",
        abstract: "",
        date: "April 25, 2018",
    },
    {
        headline: "Miro Mannino presents Qetch at CHI in Montréal",
        link: "https://dl.acm.org/citation.cfm?id=3173962",
        abstract: "",
        date: "April 23, 2018",
    },
    {
        headline: "Maeda Hanafi presents SEER at SIGMOD in Chicago",
        link: "https://dl.acm.org/citation.cfm?id=3056443",
        abstract: "",
        date: "May 19, 2017",
    },
    {
        headline: "Maeda Hanafi presents SEER at CHI in Denver",
        link: "https://dl.acm.org/citation.cfm?id=3025540",
        abstract: "",
        date: "May 11, 2017",
    },
]